# Generated by Django 3.0 on 2021-01-19 04:45

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('course', multiselectfield.db.fields.MultiSelectField(choices=[('pyhton', 'PYTHON'), ('django', 'DJANGO'), ('ui', 'UI')], max_length=100)),
                ('faculties', multiselectfield.db.fields.MultiSelectField(choices=[('Narayana', 'NARAYANA'), ('hari', 'HARI'), ('Mohit', 'MOHIHT')], max_length=100)),
                ('locations', multiselectfield.db.fields.MultiSelectField(choices=[('hyd', 'HEYDRABAD'), ('up', 'UP'), ('bang', 'BANGLURU')], max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('start_data', models.DateField(max_length=31)),
            ],
        ),
    ]
