# Generated by Django 3.1.4 on 2021-11-01 03:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('enquiryformapp', '0002_auto_20210119_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry_data',
            name='color',
            field=models.CharField(choices=[('green', 'GREEEN'), ('red', 'RED'), ('borwn', 'Brown'), ('white', 'White'), ('Black', 'Black')], default='White', max_length=10),
        ),
        migrations.AlterField(
            model_name='enquiry_data',
            name='course',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('python', 'PYTHON'), ('django', 'DJANGO'), ('ui', 'UI')], max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry_data',
            name='faculties',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Narayana', 'NARAYANA'), ('hari', 'HARI'), ('Mohit', 'MOHIT')], max_length=100),
        ),
    ]
